// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NullValue {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InternalId {
    #[prost(uint64, tag = "1")]
    pub table: u64,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GraphValue {
    #[prost(oneof = "graph_value::Value", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11")]
    pub value: ::core::option::Option<graph_value::Value>,
}
/// Nested message and enum types in `GraphValue`.
pub mod graph_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        NullValue(super::NullValue),
        #[prost(bool, tag = "2")]
        BoolValue(bool),
        #[prost(int64, tag = "3")]
        IntValue(i64),
        #[prost(double, tag = "4")]
        FloatValue(f64),
        #[prost(string, tag = "5")]
        StringValue(::prost::alloc::string::String),
        #[prost(message, tag = "6")]
        ListValue(super::ListValue),
        #[prost(message, tag = "7")]
        MapValue(super::MapValue),
        #[prost(message, tag = "8")]
        NodeValue(super::NodeValue),
        #[prost(message, tag = "9")]
        RelValue(super::RelValue),
        #[prost(message, tag = "10")]
        PathValue(super::PathValue),
        #[prost(message, tag = "11")]
        UnionValue(::prost::alloc::boxed::Box<super::UnionValue>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListValue {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<GraphValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapEntry {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<GraphValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapValue {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<MapEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeValue {
    #[prost(message, optional, tag = "1")]
    pub id: ::core::option::Option<InternalId>,
    #[prost(string, tag = "2")]
    pub label: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub properties: ::prost::alloc::vec::Vec<MapEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelValue {
    #[prost(message, optional, tag = "1")]
    pub id: ::core::option::Option<InternalId>,
    #[prost(string, tag = "2")]
    pub label: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub src: ::core::option::Option<InternalId>,
    #[prost(message, optional, tag = "4")]
    pub dst: ::core::option::Option<InternalId>,
    #[prost(message, repeated, tag = "5")]
    pub properties: ::prost::alloc::vec::Vec<MapEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PathValue {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<GraphValue>,
    #[prost(message, repeated, tag = "2")]
    pub rels: ::prost::alloc::vec::Vec<GraphValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnionValue {
    #[prost(string, tag = "1")]
    pub tag: ::prost::alloc::string::String,
    #[prost(message, optional, boxed, tag = "2")]
    pub value: ::core::option::Option<::prost::alloc::boxed::Box<GraphValue>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Row {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<GraphValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JournalEntry {
    #[prost(uint64, tag = "1")]
    pub sequence: u64,
    #[prost(string, tag = "2")]
    pub query: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub params: ::prost::alloc::vec::Vec<MapEntry>,
    #[prost(int64, tag = "4")]
    pub timestamp_ms: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SnapshotMeta {
    #[prost(uint64, tag = "1")]
    pub sequence: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub chain_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "3")]
    pub timestamp_ms: i64,
    #[prost(string, tag = "4")]
    pub version: ::prost::alloc::string::String,
}
