// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NullValue {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InternalId {
    #[prost(uint64, tag = "1")]
    pub table: u64,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GraphValue {
    #[prost(oneof = "graph_value::Value", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11")]
    pub value: ::core::option::Option<graph_value::Value>,
}
/// Nested message and enum types in `GraphValue`.
pub mod graph_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        NullValue(super::NullValue),
        #[prost(bool, tag = "2")]
        BoolValue(bool),
        #[prost(int64, tag = "3")]
        IntValue(i64),
        #[prost(double, tag = "4")]
        FloatValue(f64),
        #[prost(string, tag = "5")]
        StringValue(::prost::alloc::string::String),
        #[prost(message, tag = "6")]
        ListValue(super::ListValue),
        #[prost(message, tag = "7")]
        MapValue(super::MapValue),
        #[prost(message, tag = "8")]
        NodeValue(super::NodeValue),
        #[prost(message, tag = "9")]
        RelValue(super::RelValue),
        #[prost(message, tag = "10")]
        PathValue(super::PathValue),
        #[prost(message, tag = "11")]
        UnionValue(::prost::alloc::boxed::Box<super::UnionValue>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListValue {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<GraphValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapEntry {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<GraphValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapValue {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<MapEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeValue {
    #[prost(message, optional, tag = "1")]
    pub id: ::core::option::Option<InternalId>,
    #[prost(string, tag = "2")]
    pub label: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub properties: ::prost::alloc::vec::Vec<MapEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelValue {
    #[prost(message, optional, tag = "1")]
    pub id: ::core::option::Option<InternalId>,
    #[prost(string, tag = "2")]
    pub label: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub src: ::core::option::Option<InternalId>,
    #[prost(message, optional, tag = "4")]
    pub dst: ::core::option::Option<InternalId>,
    #[prost(message, repeated, tag = "5")]
    pub properties: ::prost::alloc::vec::Vec<MapEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PathValue {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<GraphValue>,
    #[prost(message, repeated, tag = "2")]
    pub rels: ::prost::alloc::vec::Vec<GraphValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnionValue {
    #[prost(string, tag = "1")]
    pub tag: ::prost::alloc::string::String,
    #[prost(message, optional, boxed, tag = "2")]
    pub value: ::core::option::Option<::prost::alloc::boxed::Box<GraphValue>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Row {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<GraphValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientMessage {
    #[prost(oneof = "client_message::Msg", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9")]
    pub msg: ::core::option::Option<client_message::Msg>,
}
/// Nested message and enum types in `ClientMessage`.
pub mod client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Hello(super::Hello),
        #[prost(message, tag = "2")]
        Execute(super::Execute),
        #[prost(message, tag = "3")]
        Begin(super::Begin),
        #[prost(message, tag = "4")]
        Commit(super::Commit),
        #[prost(message, tag = "5")]
        Rollback(super::Rollback),
        #[prost(message, tag = "6")]
        Batch(super::Batch),
        #[prost(message, tag = "7")]
        Fetch(super::Fetch),
        #[prost(message, tag = "8")]
        CloseStream(super::CloseStream),
        #[prost(message, tag = "9")]
        Close(super::Close),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Hello {
    #[prost(string, optional, tag = "1")]
    pub token: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Execute {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub params: ::prost::alloc::vec::Vec<MapEntry>,
    #[prost(string, optional, tag = "3")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "4")]
    pub fetch_size: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Begin {
    #[prost(string, optional, tag = "1")]
    pub mode: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Commit {
    #[prost(string, optional, tag = "1")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Rollback {
    #[prost(string, optional, tag = "1")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchStatement {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub params: ::prost::alloc::vec::Vec<MapEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Batch {
    #[prost(message, repeated, tag = "1")]
    pub statements: ::prost::alloc::vec::Vec<BatchStatement>,
    #[prost(string, optional, tag = "2")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Fetch {
    #[prost(uint64, tag = "1")]
    pub stream_id: u64,
    #[prost(string, optional, tag = "2")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CloseStream {
    #[prost(uint64, tag = "1")]
    pub stream_id: u64,
    #[prost(string, optional, tag = "2")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Close {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerMessage {
    #[prost(oneof = "server_message::Msg", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10")]
    pub msg: ::core::option::Option<server_message::Msg>,
}
/// Nested message and enum types in `ServerMessage`.
pub mod server_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        HelloOk(super::HelloOk),
        #[prost(message, tag = "2")]
        HelloError(super::HelloError),
        #[prost(message, tag = "3")]
        Result(super::Result),
        #[prost(message, tag = "4")]
        Error(super::Error),
        #[prost(message, tag = "5")]
        BeginOk(super::BeginOk),
        #[prost(message, tag = "6")]
        CommitOk(super::CommitOk),
        #[prost(message, tag = "7")]
        RollbackOk(super::RollbackOk),
        #[prost(message, tag = "8")]
        BatchResult(super::BatchResult),
        #[prost(message, tag = "9")]
        CloseStreamOk(super::CloseStreamOk),
        #[prost(message, tag = "10")]
        CloseOk(super::CloseOk),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HelloOk {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HelloError {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Result {
    #[prost(string, repeated, tag = "1")]
    pub columns: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "2")]
    pub rows: ::prost::alloc::vec::Vec<Row>,
    #[prost(double, tag = "3")]
    pub timing_ms: f64,
    #[prost(string, optional, tag = "4")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "5")]
    pub stream_id: ::core::option::Option<u64>,
    #[prost(bool, optional, tag = "6")]
    pub has_more: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Error {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BeginOk {
    #[prost(string, optional, tag = "1")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommitOk {
    #[prost(string, optional, tag = "1")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RollbackOk {
    #[prost(string, optional, tag = "1")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchResultEntry {
    #[prost(oneof = "batch_result_entry::Entry", tags = "1, 2")]
    pub entry: ::core::option::Option<batch_result_entry::Entry>,
}
/// Nested message and enum types in `BatchResultEntry`.
pub mod batch_result_entry {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Entry {
        #[prost(message, tag = "1")]
        Result(super::Result),
        #[prost(message, tag = "2")]
        Error(super::Error),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchResult {
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<BatchResultEntry>,
    #[prost(string, optional, tag = "2")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CloseStreamOk {
    #[prost(uint64, tag = "1")]
    pub stream_id: u64,
    #[prost(string, optional, tag = "2")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CloseOk {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JournalEntry {
    #[prost(uint64, tag = "1")]
    pub sequence: u64,
    #[prost(string, tag = "2")]
    pub query: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub params: ::prost::alloc::vec::Vec<MapEntry>,
    #[prost(int64, tag = "4")]
    pub timestamp_ms: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SnapshotMeta {
    #[prost(uint64, tag = "1")]
    pub sequence: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub chain_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag = "3")]
    pub timestamp_ms: i64,
    #[prost(string, tag = "4")]
    pub version: ::prost::alloc::string::String,
}
